# AUTOGENERATED! DO NOT EDIT! File to edit: 000_exp_01.ipynb (unless otherwise specified).

__all__ = ['run_params', 'experiment']

# Cell
from kirby.experiment import Experiment
from kirby.run_params import RunParams
import wandb

wandb.login()

run_params = RunParams(run_name='no_augmentation', debug=False)
experiment = Experiment(run_params)
experiment.run()
