# AUTOGENERATED! DO NOT EDIT! File to edit: 09_create_database_tables.ipynb (unless otherwise specified).

__all__ = ['wjd', 'items_list', 'items', 'max_entities', 'property_list', 'aliases', 'fix_label', 'f']

# Cell
# Package to read the the JSON dump
from qwikidata.json_dump import WikidataJsonDump
from .properties import properties

# Cell
wjd = WikidataJsonDump('latest-all.json.bz2') # put the name of the JsonDump here
items_list = [] # This will hold the data for the items
items = {}  # Connected items go in the objects dictionary
max_entities = 100  # Variable to stop the program during testing
property_list = properties()  # List of all properties
aliases = []  # List of all aliases

# Cell
# Make sure all string with apostrophes have an scape character for sql
def fix_label(label):
    index = 0
    while index < len(label):
        if label[index] == '\'':
            label = label[:index] + '\'' + label[index:]
            index += 1
        index += 1
    return label

# Cell
f = open("sql_statements.txt", "a", encoding="utf-8")