# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"KnowledgeBaseAccessor": "00_knowledge_base_accessor.ipynb"}

modules = ["knowledge_base_accessor.py"]

doc_url = "https://rmorain.github.io/kirby/"

git_url = "https://github.com/rmorain/kirby/tree/master/"

def custom_doc_links(name): return None
