# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"KnowledgeBaseAccessor": "00_knowledge_base_accessor.ipynb",
         "kirby_database_builder": "01_kirby_database_builder.ipynb",
         "StatementClassifier": "02_statement_classifer.ipynb",
         "QueryGenerator": "03_query_generator.ipynb",
         "Experiment": "04_experiment.ipynb",
         "RunParams": "05_run_parameters.ipynb",
         "BasicModel": "06_basic_model.ipynb",
         "prepare_data": "07_prepare_data.ipynb",
         "tokenize": "07_prepare_data.ipynb",
         "prepare_ds": "07_prepare_data.ipynb"}

modules = ["knowledge_base_accessor.py",
           "kirby_dataset_builder.py",
           "statement_classifier.py",
           "query_generator.py",
           "experiment.py",
           "run_params.py",
           "basic_model.py",
           "prepare_data.py"]

doc_url = "https://rmorain.github.io/kirby/"

git_url = "https://github.com/rmorain/kirby/tree/master/"

def custom_doc_links(name): return None
