# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb (unless otherwise specified).

__all__ = ['Model']

# Cell
class Model(pl.LightningModule):
    def __init__(self):
        pass

    def prepare_data(self):
        pass

    def forward(self, x):
        pass

    def training_step(self, batch, batch_idx):
        pass

    def validation_step(self, batch, batch_idx):
        pass

    def validation_epoch_end(self, outputs):
        pass

    def train_dataloader(self):
        pass

    def val_dataloader(self):
        pass

    def configure_optimizer(self):
        pass
