# AUTOGENERATED! DO NOT EDIT! File to edit: 000_exp_02_pretrained.ipynb (unless otherwise specified).

__all__ = ['run_params', 'experiment', 'run_params', 'experiment']

# Cell
from .experiment import Experiment
from .run_params import RunParams
import wandb

wandb.login()

run_params = RunParams(run_name='no_augmentation', debug=False)
experiment = Experiment(run_params)
experiment.run()

# Cell
from .experiment import Experiment
from .run_params import RunParams
import wandb

wandb.login()

run_params = RunParams(run_name='no_augmentation_pretrained', debug=True, pretrained=True)
experiment = Experiment(run_params)
experiment.run()