# AUTOGENERATED! DO NOT EDIT! File to edit: 10_insert_to_database.ipynb (unless otherwise specified).

__all__ = ['connection', 'sql_query', 'last_line', 'crsr', 'count']

# Cell
from qwikidata.json_dump import WikidataJsonDump
import sqlite3

# Cell
connection = sqlite3.connect("wiki_database2.db") # Name of your database
sql_query = []
last_line = ''
crsr = connection.cursor()
count = 0
with open('sql_statements.txt', 'r', encoding="utf-8") as file: # Name of the file where you wrote wikidata to
    while True:
        line = file.readline()
        if not line:
            break
        if line == '\n':
            # print('Hello')
            # print(sql_query)
            file.readline()
            file.readline()
            file.readline()
            # sql_command = '\"\"\"{}\"\"\"'.format(sql_query)
            try:
                if len(sql_query) == 0 or sql_query[0] == "INSERT INTO Aliases\n" or sql_query[1] == "INSERT INTO Aliases\n":
                    sql_query.clear()
                    continue
                if sql_query[-1][-1] == ',':
                    sql_query[-1] = sql_query[-1][:-1] + ';'

                crsr.execute(''.join(sql_query))
            except Exception as e:
                print(e)
                for line in sql_query:
                    print(line, end='')
                print('Something went wrong')
                break
            connection.commit()
            sql_query.clear()

        sql_query.append(line)

# close the connection
connection.close()
