# AUTOGENERATED! DO NOT EDIT! File to edit: 00_knowledge_base_accessor.ipynb (unless otherwise specified).

__all__ = ['KnowledgeBaseAccessor']

# Cell
class KnowledgeBaseAccessor():
    "Class to access the Wikidata Knowledge Base"

    def query(self, q):
        "Query the Wikidata knowledge base"
        return f'Performing query {q}'
