# AUTOGENERATED! DO NOT EDIT! File to edit: 03_query_generator.ipynb (unless otherwise specified).

__all__ = ['QueryGenerator']

# Cell
class QueryGenerator():
    def __init__(self):
        pass

    def generate(self, x):
        "Generate an query from input x"
        pass