# AUTOGENERATED! DO NOT EDIT! File to edit: 06_basic_model.ipynb (unless otherwise specified).

__all__ = ['RunParams', 'Model']

# Cell
class RunParams():
    def __init__(self,
                model='gpt2',
                data_dir = 'data',
                data_files = {'train': ['wiki.train.raw'], 'valid': ['wiki.valid.raw'], 'test': ['wiki.test.raw']},
                max_epochs=1,
                debug=True,
                batch_size=8,
                data_set_percentage=1,
                seq_length=32,
                statement_length=16,
                momentum=.9,
                lr=1e-2,
                repo='wikitext-103-raw-v1',
                num_workers=2,
                kb_statements_file=None,
                run_name='test',
                project_name='test-project'
            ):

        self.model = model
        self.data_files = data_files
        self.max_epochs = max_epochs
        self.debug = debug
        self.batch_size = batch_size
        self.data_set_percentage = data_set_percentage
        self.seq_length = seq_length
        self.statement_length = statement_length
        self.momentum = momentum
        self.lr = lr
        self.repo = repo
        self.num_workers = num_workers
        self.kb_statements_file = kb_statements_file


# Cell
import pytorch_lightning as pl

# Cell
class Model(pl.LightningModule):
    def __init__(self):
        pass

    def prepare_data(self):
        pass

    def forward(self, x):
        pass

    def training_step(self, batch, batch_idx):
        pass

    def validation_step(self, batch, batch_idx):
        pass

    def validation_epoch_end(self, outputs):
        pass

    def train_dataloader(self):
        pass

    def val_dataloader(self):
        pass

    def configure_optimizer(self):
        pass