# AUTOGENERATED! DO NOT EDIT! File to edit: 02_statement_classifer.ipynb (unless otherwise specified).

__all__ = ['StatementClassifier']

# Cell
class StatementClassifier():
    def __init__(self):
        pass

    def classify(self, x, statements):
        "Given an input x, classify statements as True or False"
        pass